# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f81d2f86e80052fbbe42c9c69034f54e8999b041cb7c9938441796ff451aa87b0b15ac29ed6ddea4b64c39475a67cd7d365bae7405a43167745260fff9a48984

test:
  secret_key_base: 4d266849b198453c578b942e437f3bed07981566f354fe8cfaf44e7fbeca119e6e5eafb889f8b898af5e61fb6677932878c79ffe78375981b018a0151b9fe4a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
